[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://office-management-fsy7.onrender.com"

# Environment variables for production
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://office-management-fsy7.onrender.com"
  NODE_ENV = "production"

# Environment variables for deploy preview
[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://office-management-fsy7.onrender.com"
  NODE_ENV = "production"

# تم تعطيل Netlify Next.js plugin لأننا نستخدم static export
# [[plugins]]
# package = "@netlify/plugin-nextjs"

# Redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle Next.js routing
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes should not be cached
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0" 